# Generated by Django 5.2.6 on 2025-12-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('doc_name', models.CharField(blank=True, max_length=200)),
                ('doc_type', models.CharField(blank=True, max_length=200)),
                ('from_lang', models.CharField(blank=True, max_length=200)),
                ('to_lang', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='input_documents/')),
                ('translation_format', models.CharField(blank=True, max_length=200)),
                ('task_process_status', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'input_documents',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('lang_title', models.CharField(blank=True, max_length=200)),
                ('lang_keyword', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
    ]
